const currencyCodes = [
  { label: "Afghanistan", value: "AFN", flag: "https://flagcdn.com/af.svg" },
  { label: "Albania", value: "ALL", flag: "https://flagcdn.com/al.svg" },
  { label: "Algeria", value: "DZD", flag: "https://flagcdn.com/dz.svg" },
  { label: "Andorra", value: "EUR", flag: "https://flagcdn.com/ad.svg" },
  { label: "Angola", value: "AOA", flag: "https://flagcdn.com/ao.svg" },
  { label: "Antigua and Barbuda", value: "XCD", flag: "https://flagcdn.com/ag.svg" },
  { label: "Argentina", value: "ARS", flag: "https://flagcdn.com/ar.svg" },
  { label: "Armenia", value: "AMD", flag: "https://flagcdn.com/am.svg" },
  { label: "Australia", value: "AUD", flag: "https://flagcdn.com/au.svg" },
  { label: "Austria", value: "EUR", flag: "https://flagcdn.com/at.svg" },
  { label: "Azerbaijan", value: "AZN", flag: "https://flagcdn.com/az.svg" },
  { label: "Bahamas", value: "BSD", flag: "https://flagcdn.com/bs.svg" },
  { label: "Bahrain", value: "BHD", flag: "https://flagcdn.com/bh.svg" },
  { label: "Bangladesh", value: "BDT", flag: "https://flagcdn.com/bd.svg" },
  { label: "Barbados", value: "BBD", flag: "https://flagcdn.com/bb.svg" },
  { label: "Belarus", value: "BYN", flag: "https://flagcdn.com/by.svg" },
  { label: "Belgium", value: "EUR", flag: "https://flagcdn.com/be.svg" },
  { label: "Belize", value: "BZD", flag: "https://flagcdn.com/bz.svg" },
  { label: "Benin", value: "XOF", flag: "https://flagcdn.com/bj.svg" },
  { label: "Bhutan", value: "BTN", flag: "https://flagcdn.com/bt.svg" },
  { label: "Bolivia", value: "BOB", flag: "https://flagcdn.com/bo.svg" },
  { label: "Bosnia and Herzegovina", value: "BAM", flag: "https://flagcdn.com/ba.svg" },
  { label: "Botswana", value: "BWP", flag: "https://flagcdn.com/bw.svg" },
  { label: "Brazil", value: "BRL", flag: "https://flagcdn.com/br.svg" },
  { label: "Brunei", value: "BND", flag: "https://flagcdn.com/bn.svg" },
  { label: "Bulgaria", value: "BGN", flag: "https://flagcdn.com/bg.svg" },
  { label: "Burkina Faso", value: "XOF", flag: "https://flagcdn.com/bf.svg" },
  { label: "Burundi", value: "BIF", flag: "https://flagcdn.com/bi.svg" },
  { label: "Cambodia", value: "KHR", flag: "https://flagcdn.com/kh.svg" },
  { label: "Cameroon", value: "XAF", flag: "https://flagcdn.com/cm.svg" },
  { label: "Canada", value: "CAD", flag: "https://flagcdn.com/ca.svg" },
  { label: "Cape Verde", value: "CVE", flag: "https://flagcdn.com/cv.svg" },
  { label: "Central African Republic", value: "XAF", flag: "https://flagcdn.com/cf.svg" },
  { label: "Chad", value: "XAF", flag: "https://flagcdn.com/td.svg" },
  { label: "Chile", value: "CLP", flag: "https://flagcdn.com/cl.svg" },
  { label: "China", value: "CNY", flag: "https://flagcdn.com/cn.svg" },
  { label: "Colombia", value: "COP", flag: "https://flagcdn.com/co.svg" },
  { label: "Comoros", value: "KMF", flag: "https://flagcdn.com/km.svg" },
  { label: "Congo", value: "XAF", flag: "https://flagcdn.com/cg.svg" },
  { label: "Costa Rica", value: "CRC", flag: "https://flagcdn.com/cr.svg" },
  { label: "Croatia", value: "HRK", flag: "https://flagcdn.com/hr.svg" },
  { label: "Cuba", value: "CUP", flag: "https://flagcdn.com/cu.svg" },
  { label: "Cyprus", value: "EUR", flag: "https://flagcdn.com/cy.svg" },
  { label: "Czech Republic", value: "CZK", flag: "https://flagcdn.com/cz.svg" },
  { label: "Democratic Republic of the Congo", value: "CDF", flag: "https://flagcdn.com/cd.svg" },
  { label: "Denmark", value: "DKK", flag: "https://flagcdn.com/dk.svg" },
  { label: "Djibouti", value: "DJF", flag: "https://flagcdn.com/dj.svg" },
  { label: "Dominica", value: "XCD", flag: "https://flagcdn.com/dm.svg" },
  { label: "Dominican Republic", value: "DOP", flag: "https://flagcdn.com/do.svg" },
  { label: "East Timor", value: "USD", flag: "https://flagcdn.com/tl.svg" },
  { label: "Ecuador", value: "USD", flag: "https://flagcdn.com/ec.svg" },
  { label: "Egypt", value: "EGP", flag: "https://flagcdn.com/eg.svg" },
  { label: "El Salvador", value: "USD", flag: "https://flagcdn.com/sv.svg" },
  { label: "Equatorial Guinea", value: "XAF", flag: "https://flagcdn.com/gq.svg" },
  { label: "Eritrea", value: "ERN", flag: "https://flagcdn.com/er.svg" },
  { label: "Estonia", value: "EUR", flag: "https://flagcdn.com/ee.svg" },
  { label: "Ethiopia", value: "ETB", flag: "https://flagcdn.com/et.svg" },
  { label: "Fiji", value: "FJD", flag: "https://flagcdn.com/fj.svg" },
  { label: "Finland", value: "EUR", flag: "https://flagcdn.com/fi.svg" },
  { label: "France", value: "EUR", flag: "https://flagcdn.com/fr.svg" },
  { label: "Gabon", value: "XAF", flag: "https://flagcdn.com/ga.svg" },
  { label: "Gambia", value: "GMD", flag: "https://flagcdn.com/gm.svg" },
  { label: "Georgia", value: "GEL", flag: "https://flagcdn.com/ge.svg" },
  { label: "Germany", value: "EUR", flag: "https://flagcdn.com/de.svg" },
  { label: "Ghana", value: "GHS", flag: "https://flagcdn.com/gh.svg" },
  { label: "Greece", value: "EUR", flag: "https://flagcdn.com/gr.svg" },
  { label: "Grenada", value: "XCD", flag: "https://flagcdn.com/gd.svg" },
  { label: "Guatemala", value: "GTQ", flag: "https://flagcdn.com/gt.svg" },
  { label: "Guinea", value: "GNF", flag: "https://flagcdn.com/gn.svg" },
  { label: "Guinea-Bissau", value: "XOF", flag: "https://flagcdn.com/gw.svg" },
  { label: "Guyana", value: "GYD", flag: "https://flagcdn.com/gy.svg" },
  { label: "Haiti", value: "HTG", flag: "https://flagcdn.com/ht.svg" },
  { label: "Honduras", value: "HNL", flag: "https://flagcdn.com/hn.svg" },
  { label: "Hungary", value: "HUF", flag: "https://flagcdn.com/hu.svg" },
  { label: "Iceland", value: "ISK", flag: "https://flagcdn.com/is.svg" },
  { label: "India", value: "INR", flag: "https://flagcdn.com/in.svg" },
  { label: "Indonesia", value: "IDR", flag: "https://flagcdn.com/id.svg" },
  { label: "Iran", value: "IRR", flag: "https://flagcdn.com/ir.svg" },
  { label: "Iraq", value: "IQD", flag: "https://flagcdn.com/iq.svg" },
  { label: "Ireland", value: "EUR", flag: "https://flagcdn.com/ie.svg" },
  { label: "Israel", value: "ILS", flag: "https://flagcdn.com/il.svg" },
  { label: "Italy", value: "EUR", flag: "https://flagcdn.com/it.svg" },
  { label: "Ivory Coast", value: "XOF", flag: "https://flagcdn.com/ci.svg" },
  { label: "Jamaica", value: "JMD", flag: "https://flagcdn.com/jm.svg" },
  { label: "Japan", value: "JPY", flag: "https://flagcdn.com/jp.svg" },
  { label: "Jordan", value: "JOD", flag: "https://flagcdn.com/jo.svg" },
  { label: "Kazakhstan", value: "KZT", flag: "https://flagcdn.com/kz.svg" },
  { label: "Kenya", value: "KES", flag: "https://flagcdn.com/ke.svg" },
  { label: "Kiribati", value: "AUD", flag: "https://flagcdn.com/ki.svg" },
  { label: "Kuwait", value: "KWD", flag: "https://flagcdn.com/kw.svg" },
  { label: "Kyrgyzstan", value: "KGS", flag: "https://flagcdn.com/kg.svg" },
  { label: "Laos", value: "LAK", flag: "https://flagcdn.com/la.svg" },
  { label: "Latvia", value: "EUR", flag: "https://flagcdn.com/lv.svg" },
  { label: "Lebanon", value: "LBP", flag: "https://flagcdn.com/lb.svg" },
  { label: "Lesotho", value: "LSL", flag: "https://flagcdn.com/ls.svg" },
  { label: "Liberia", value: "LRD", flag: "https://flagcdn.com/lr.svg" },
  { label: "Libya", value: "LYD", flag: "https://flagcdn.com/ly.svg" },
  { label: "Liechtenstein", value: "CHF", flag: "https://flagcdn.com/li.svg" },
  { label: "Lithuania", value: "EUR", flag: "https://flagcdn.com/lt.svg" },
  { label: "Luxembourg", value: "EUR", flag: "https://flagcdn.com/lu.svg" },
  { label: "Madagascar", value: "MGA", flag: "https://flagcdn.com/mg.svg" },
  { label: "Malawi", value: "MWK", flag: "https://flagcdn.com/mw.svg" },
  { label: "Malaysia", value: "MYR", flag: "https://flagcdn.com/my.svg" },
  { label: "Maldives", value: "MVR", flag: "https://flagcdn.com/mv.svg" },
  { label: "Mali", value: "XOF", flag: "https://flagcdn.com/ml.svg" },
  { label: "Malta", value: "EUR", flag: "https://flagcdn.com/mt.svg" },
  { label: "Marshall Islands", value: "USD", flag: "https://flagcdn.com/mh.svg" },
  { label: "Mauritania", value: "MRU", flag: "https://flagcdn.com/mr.svg" },
  { label: "Mauritius", value: "MUR", flag: "https://flagcdn.com/mu.svg" },
  { label: "Mexico", value: "MXN", flag: "https://flagcdn.com/mx.svg" },
  { label: "Micronesia", value: "USD", flag: "https://flagcdn.com/fm.svg" },
  { label: "Moldova", value: "MDL", flag: "https://flagcdn.com/md.svg" },
  { label: "Monaco", value: "EUR", flag: "https://flagcdn.com/mc.svg" },
  { label: "Mongolia", value: "MNT", flag: "https://flagcdn.com/mn.svg" },
  { label: "Montenegro", value: "EUR", flag: "https://flagcdn.com/me.svg" },
  { label: "Morocco", value: "MAD", flag: "https://flagcdn.com/ma.svg" },
  { label: "Mozambique", value: "MZN", flag: "https://flagcdn.com/mz.svg" },
  { label: "Myanmar", value: "MMK", flag: "https://flagcdn.com/mm.svg" },
  { label: "Namibia", value: "NAD", flag: "https://flagcdn.com/na.svg" },
  { label: "Nauru", value: "AUD", flag: "https://flagcdn.com/nr.svg" },
  { label: "Nepal", value: "NPR", flag: "https://flagcdn.com/np.svg" },
  { label: "Netherlands", value: "EUR", flag: "https://flagcdn.com/nl.svg" },
  { label: "New Zealand", value: "NZD", flag: "https://flagcdn.com/nz.svg" },
  { label: "Nicaragua", value: "NIO", flag: "https://flagcdn.com/ni.svg" },
  { label: "Niger", value: "XOF", flag: "https://flagcdn.com/ne.svg" },
  { label: "Nigeria", value: "NGN", flag: "https://flagcdn.com/ng.svg" },
  { label: "North Korea", value: "KPW", flag: "https://flagcdn.com/kp.svg" },
  { label: "North Macedonia", value: "MKD", flag: "https://flagcdn.com/mk.svg" },
  { label: "Norway", value: "NOK", flag: "https://flagcdn.com/no.svg" },
  { label: "Oman", value: "OMR", flag: "https://flagcdn.com/om.svg" },
  { label: "Pakistan", value: "PKR", flag: "https://flagcdn.com/pk.svg" },
  { label: "Palau", value: "USD", flag: "https://flagcdn.com/pw.svg" },
  { label: "Palestine", value: "ILS", flag: "https://flagcdn.com/ps.svg" },
  { label: "Panama", value: "PAB", flag: "https://flagcdn.com/pa.svg" },
  { label: "Papua New Guinea", value: "PGK", flag: "https://flagcdn.com/pg.svg" },
  { label: "Paraguay", value: "PYG", flag: "https://flagcdn.com/py.svg" },
  { label: "Peru", value: "PEN", flag: "https://flagcdn.com/pe.svg" },
  { label: "Philippines", value: "PHP", flag: "https://flagcdn.com/ph.svg" },
  { label: "Poland", value: "PLN", flag: "https://flagcdn.com/pl.svg" },
  { label: "Portugal", value: "EUR", flag: "https://flagcdn.com/pt.svg" },
  { label: "Qatar", value: "QAR", flag: "https://flagcdn.com/qa.svg" },
  { label: "Romania", value: "RON", flag: "https://flagcdn.com/ro.svg" },
  { label: "Russia", value: "RUB", flag: "https://flagcdn.com/ru.svg" },
  { label: "Rwanda", value: "RWF", flag: "https://flagcdn.com/rw.svg" },
  { label: "Saint Kitts and Nevis", value: "XCD", flag: "https://flagcdn.com/kn.svg" },
  { label: "Saint Lucia", value: "XCD", flag: "https://flagcdn.com/lc.svg" },
  { label: "Saint Vincent and the Grenadines", value: "XCD", flag: "https://flagcdn.com/vc.svg" },
  { label: "Samoa", value: "WST", flag: "https://flagcdn.com/ws.svg" },
  { label: "San Marino", value: "EUR", flag: "https://flagcdn.com/sm.svg" },
  { label: "Sao Tome and Principe", value: "STN", flag: "https://flagcdn.com/st.svg" },
  { label: "Saudi Arabia", value: "SAR", flag: "https://flagcdn.com/sa.svg" },
  { label: "Senegal", value: "XOF", flag: "https://flagcdn.com/sn.svg" },
  { label: "Serbia", value: "RSD", flag: "https://flagcdn.com/rs.svg" },
  { label: "Seychelles", value: "SCR", flag: "https://flagcdn.com/sc.svg" },
  { label: "Sierra Leone", value: "SLL", flag: "https://flagcdn.com/sl.svg" },
  { label: "Singapore", value: "SGD", flag: "https://flagcdn.com/sg.svg" },
  { label: "Slovakia", value: "EUR", flag: "https://flagcdn.com/sk.svg" },
  { label: "Slovenia", value: "EUR", flag: "https://flagcdn.com/si.svg" },
  { label: "Solomon Islands", value: "SBD", flag: "https://flagcdn.com/sb.svg" },
  { label: "Somalia", value: "SOS", flag: "https://flagcdn.com/so.svg" },
  { label: "South Africa", value: "ZAR", flag: "https://flagcdn.com/za.svg" },
  { label: "South Korea", value: "KRW", flag: "https://flagcdn.com/kr.svg" },
  { label: "South Sudan", value: "SSP", flag: "https://flagcdn.com/ss.svg" },
  { label: "Spain", value: "EUR", flag: "https://flagcdn.com/es.svg" },
  { label: "Sri Lanka", value: "LKR", flag: "https://flagcdn.com/lk.svg" },
  { label: "Sudan", value: "SDG", flag: "https://flagcdn.com/sd.svg" },
  { label: "Suriname", value: "SRD", flag: "https://flagcdn.com/sr.svg" },
  { label: "Sweden", value: "SEK", flag: "https://flagcdn.com/se.svg" },
  { label: "Switzerland", value: "CHF", flag: "https://flagcdn.com/ch.svg" },
  { label: "Syria", value: "SYP", flag: "https://flagcdn.com/sy.svg" },
  { label: "Taiwan", value: "TWD", flag: "https://flagcdn.com/tw.svg" },
  { label: "Tajikistan", value: "TJS", flag: "https://flagcdn.com/tj.svg" },
  { label: "Tanzania", value: "TZS", flag: "https://flagcdn.com/tz.svg" },
  { label: "Thailand", value: "THB", flag: "https://flagcdn.com/th.svg" },
  { label: "Togo", value: "XOF", flag: "https://flagcdn.com/tg.svg" },
  { label: "Tonga", value: "TOP", flag: "https://flagcdn.com/to.svg" },
  { label: "Trinidad and Tobago", value: "TTD", flag: "https://flagcdn.com/tt.svg" },
  { label: "Tunisia", value: "TND", flag: "https://flagcdn.com/tn.svg" },
  { label: "Turkey", value: "TRY", flag: "https://flagcdn.com/tr.svg" },
  { label: "Turkmenistan", value: "TMT", flag: "https://flagcdn.com/tm.svg" },
  { label: "Tuvalu", value: "AUD", flag: "https://flagcdn.com/tv.svg" },
  { label: "Uganda", value: "UGX", flag: "https://flagcdn.com/ug.svg" },
  { label: "Ukraine", value: "UAH", flag: "https://flagcdn.com/ua.svg" },
  { label: "United Arab Emirates", value: "AED", flag: "https://flagcdn.com/ae.svg" },
  { label: "United Kingdom", value: "GBP", flag: "https://flagcdn.com/gb.svg" },
  { label: "United States", value: "USD", flag: "https://flagcdn.com/us.svg" },
  { label: "Uruguay", value: "UYU", flag: "https://flagcdn.com/uy.svg" },
  { label: "Uzbekistan", value: "UZS", flag: "https://flagcdn.com/uz.svg" },
  { label: "Vanuatu", value: "VUV", flag: "https://flagcdn.com/vu.svg" },
  { label: "Vatican City", value: "EUR", flag: "https://flagcdn.com/va.svg" },
  { label: "Venezuela", value: "VES", flag: "https://flagcdn.com/ve.svg" },
  { label: "Vietnam", value: "VND", flag: "https://flagcdn.com/vn.svg" },
  { label: "Yemen", value: "YER", flag: "https://flagcdn.com/ye.svg" },
  { label: "Zambia", value: "ZMW", flag: "https://flagcdn.com/zm.svg" },
  { label: "Zimbabwe", value: "ZWL", flag: "https://flagcdn.com/zw.svg" },
];

export default currencyCodes;